### ISSUE TITLE
Instructions to install PADRE as a feature/plugin within an Eclipse instance

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [SEALABQualityGroup/padre#1]
Ciao,
From your readme.md it is unclear whether PADRE has to be installed within an Eclipse Modeling IDE, from an update site or it consists of a number of Eclipse plugins that have to be imported into the workspace.
Could you please clarify? 
Grazie mille

**Comment by danieledipompeo** [comment]
Ciao,
I updated the PADRE [update-site](https://github.com/SEALABQualityGroup/padre-update-site/raw/master/updates/releases/oxygen/1.0.0). 

Please, follows these few installation requirements:
  - add these additional repositories:
    - Papyrus - Oxygen	[here](http://download.eclipse.org/modeling/mdt/papyrus/updates/releases/oxygen)
    - MARTE - Papyrus	[here](http://download.eclipse.org/modeling/mdt/papyrus/updates/releases/neon)
    - Epsilon 1.3 [here](http://download.eclipse.org/epsilon/1.3/updates/)
  Let us know if you get some errors during this step
![additional_repository](https://user-images.githubusercontent.com/2399323/50341767-6a2df580-0520-11e9-83d3-4dda761dda40.png)
 - Please, take care to check the option **"Contact  all update sites during install to find required software"**, as shown in the following screenshot
![needed_flag](https://user-images.githubusercontent.com/2399323/50341768-6a2df580-0520-11e9-9a8c-84e68ee30d32.png)

I successfully installed it on an Eclipse Modelling Tool version Oxygen.3a Release (4.7.3a) that you can download from [here](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-modeling-oxygen-3a-macosx-cocoa-x86_64.dmg).
Please, let us know if you get problems during the installation.
Later, I will update the readme accordingly.

best wishes
Daniele

**Comment by jesus-gorronogoitia** [comment]
Ciao @danieledipompeo 
In MegaM@Rt the common baseline Eclipse IDE for installing all the tools is Eclipse Modelling 2018-09. In WP5 we decided to freeze this one for the entire project lifetime (I hope this is not a huge obstacle for you)
Therefore, I've tried to installed PADRE in this version (not in Oxygen), using the following additional repositories:
- Papyrus: 
- MARTE: 
- Epsilon: 
but I couldn't satisfy all the PADRE dependencies:

`Cannot complete the install because of a conflicting dependency.
  Software being installed: Padre feature 1.0.0 (it.univaq.disim.sealab.padre.feature.feature.group 1.0.0)
  Software currently installed: EMF Views 0.3.0.201812101714 (org.atlanmod.emfviews.feature.feature.group 0.3.0.201812101714)
  Only one of the following can be installed at once: 
    Epsilon Object Language 1.5.1.201809302027 (org.eclipse.epsilon.eol.engine 1.5.1.201809302027)
    Epsilon Object Language 1.3.0.201812211214 (org.eclipse.epsilon.eol.engine 1.3.0.201812211214)
  Cannot satisfy dependency:
    From: Padre feature 1.0.0 (it.univaq.disim.sealab.padre.feature.feature.group 1.0.0)
    To: org.eclipse.equinox.p2.iu; org.eclipse.epsilon.eol.engine [1.3.0.201812211214,1.3.0.201812211214]
  Cannot satisfy dependency:
    From: EMF Views 0.3.0.201812101714 (org.atlanmod.emfviews.feature.feature.group 0.3.0.201812101714)
    To: org.eclipse.equinox.p2.iu; org.eclipse.epsilon.eol.engine [1.4.0,2.0.0)`

The reason is that another MegaM@Rt tool, EMFViews, requires Epsilon Object Language 1.5.1. So, if we want to offer a common Eclipse platform for all Eclipse-based MegaM@Rt tools, we need to agree on a common dependencies baseline. So, could it work for PADRE to upgrade to Epsilon 1.5.1?

Could be possible that you upgrade PADRE to be compatible with Eclipse Modelling 2018-09? You can use for this duty the efforts your institution has in WP5, T5.1.
Please, let me know.
Grazie mille
Yosu

**Comment by danieledipompeo** [comment]
Ciao @jesus-gorronogoitia 
we have just released the new [update-site](https://github.com/SEALABQualityGroup/padre-update-site/raw/master/updates/releases/oxygen/1.0.1).

Let me know if you have problems with this version.

Cheers
Daniele

**Comment by jesus-gorronogoitia** [comment]
Ciao @danieledipompeo 
I could install PADRE in Eclipse 2018-09 with this update site. Grazie mille.
I will now integrate PADRE in the common MegaM@Rt toolset
